name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:
    branches:
      - main
      - staging
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Set Python version
        run: echo "Using Python version 3.9"

      - name: Check Syntax
        run: pre-commit run --all-files

      - name: Make Migrations
        run: python manage.py makemigrations

      - name: Migration
        run: python3 manage.py migrate

      - name: Run server
        run: python3 manage.py runserver

      - name: Run Tests
        run: python manage.py test
